// ─── Hand-authored asset overrides ─────────────────────────────────────────
// cloudinary-assets.generated.ts is rewritten by scripts/sync-cloudinary-assets.ts,
// so a client whose media lives outside Cloudinary cannot be recorded there.
// Entries here win over the generated lists for the slugs they name.
//
// Values are finished URLs, not public IDs. The delivery helpers in
// lib/cloudinary.ts pass absolute URLs through untouched, and the host is
// allowed in next.config.ts for next/image.

import type { CaseAssets } from './cloudinary-assets.generated'

export const caseAssetOverrides: Record<string, CaseAssets> = {
  'aahaa': {
    images: [
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR13%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR13%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR15%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR17%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR17%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR19%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR20%20SLIDE%201.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR20%20SLIDE%202.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR20%20SLIDE%203.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR20%20SLIDE%204.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR20%20SLIDE%205.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20APR26%20Tuesday%20Promo.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUL06%20Game%20on.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUL07%204TH%20OF%20JULY.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUL08%20Catering%20Special.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUL09%20We%20open%20late%20for%C2%A0FIFA.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUL20%20Mandi%E2%80%99s%20Cupon-01.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUN01%20Private%20room%20poster.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUN06%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUN08%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUN11%20Fathers%20Day.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20JUN12%20Chef%20specialty%20dishes.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY14%20Chef%20new%20experience%20presentation.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY26%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY26%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY29%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY29%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY29%20Slide%204.jpg',
      'https://cdn.atriumad.com/clients/AAHA/photos/AAHA_%20MAY30%20Regular%20Buffet.jpg',
    ],
    videos: [
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUL12%20Compilation%202%20Standing%C2%A0Up.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUL13%20New%20chef%20specialties%20general%C2%A0presentation.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUL15%20New%20chef%20specialty%20Zafrani%20Chicken%C2%A0Tikka.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUL16%20New%20chef%20specialty%20lamb%C2%A0burger.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUN25%20BTS-Process-result.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUN26%20Banquet%20General%20Compilation.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20JUN30%20Lunch%20buffet%20compilation%20people%20and%20food%C2%A0focus.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20MAY16%20Compilation%201-Dinner%20on%20the%C2%A0Patio.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_%20MAY18%20Compialion%20Food%28Cooking%C2%A0and%C2%A0Plating%C2%A0%29.mp4',
      'https://cdn.atriumad.com/clients/AAHA/reels/AAHA_JUN04%20Compialion%20Food%28Serving%C2%A0and%C2%A0lifestyle%29.mp4',
    ],
  },
  'taco-naco': {
    images: [
      'https://cdn.atriumad.com/clients/TNKC/photos/Artboard%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/Artboard%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/Artboard%203.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR01%20Post%20Easter%20brunch%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR05%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR05%20Slide%205.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR19%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR19%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR24%20Photo%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR24%20Photo%203.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20APR31%20farmers%20Market.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20AUG15%20Churros-Proof%20of%20love.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL13%20Nacho%20Bowl%20Wednesday.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL14%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL14%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL17%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL17%20Slide%204.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL18%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUL18%20Slide%204.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUN05%20Ceviche%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUN07%20Fathers%20day.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20JUN07%20Reminder_%20tequila.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAR13%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY27%20Ceviche.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY31%20Creative%20Post%204.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY32%20Creative%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY34%20Creative%20Post%203%20(1).jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY34%20Creative%20Post%203.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY36%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_%20MAY38%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_APR16_CREATIVE%20POST.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_JUN26%20Happy%20Hour%20Story.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_JUN26%20Happy%20Hour.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR01%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR02%20SLIDE%201.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR02%20SLIDE%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR10%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR11%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TNKC/photos/TNKC_MAR12%20Slide1_.jpg',
    ],
    videos: [
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20APR12_Margarita%201%20.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20APR29_Ceviche%20Tostada-.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20AUG05%20Cochinita%20Pibil%20-Prep%20Reedit.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20AUG06%20Loaded%20Nachos%20-Prep%20Reedit-.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20AUG08%20Drawing%20Transitions.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20AUG11%20DIVIDED%20SCREEN.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20JUL01%20Chilaquiles.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20JUL06%20Tosta-Guac%20Build%20Up.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20JUL12%20Compilation%20Single%20Item.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20JUN30%20Fan%20Fest%20FIFA%20food%20truck-.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20MAY01%20Football%20Video-.mp4',
      'https://cdn.atriumad.com/clients/TNKC/reels/TNKC_%20MAY06%20Tequila%20Shoot%20Video-.mp4',
    ],
  },
  'taha': {
    images: [
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20APR19%20HAPPY%20HOUR.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20APR36%205%20Mayo%20save%20the%20date.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20APR39%20VIP%20Promo_.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG%20Photo%20editing%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG%20Photo%20editing%203.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG08%20Camarones%20Tocinetaa%20-2.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG09%20House%20salad%20-2.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG10%20Jaiba%20tacos%20-2.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG15%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG15%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG15%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG17%20Happy%20Hour.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG28%20Lifestyle-Date%20Night.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20AUG31%20Slide%204.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL08%20Seafood%20tower%20Post.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL09%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL10%20Brunch%20Post.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL13%20Crab%20legs%20post.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL14%20La%20chismosa%20Post.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUL15%20Lifestyle%20Photo.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUN28%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUN30%20Slide%205.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20JUN32%20Game%20day%20post.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20MAY17%20Slide%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20MAY17%20Slide%203.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20MAY31%20Chef%20michelin%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_%20MAY36%20POSTER.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_APR12%20March%20madness%20promo.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_APR15%20Photo%202.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_AUG16%20Free%20Valet.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_JUL12%20Slide%201.jpg',
      'https://cdn.atriumad.com/clients/TAHA/photos/TAHA_JUN23%20Fathers%20day_.jpg',
    ],
    videos: [
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20APR%20COMPILATION%204.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20APR24%20Lifestyle%202%20Patio.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20APR25%20Wagyu%20video.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20AUG03%20Our%20Camera%20Roll%20-vibe.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20AUG05%20When%20i%20Say-Vibe.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20AUG22%20Grilled%20Salmon%20Prep.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20AUG30%20Oysters%20Day.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20JUL19%20Brunch%20Coffee.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20MAR13%20tacos%20de%20pescado.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20MAR17%20COMPILATION%203%20VIBE.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20MAR31%20Dinner%20w%20friends%20aesthetic%20reel.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_%20MAY24%20Camera%20photos%20trend.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_FEB31%20croquetas.mp4',
      'https://cdn.atriumad.com/clients/TAHA/reels/TAHA_MAR30%20Fidel%20Video.mp4',
    ],
  },
}
