import type { SystemDefinition } from "@/lib/health/types"

/**
 * No default on purpose. The value the app itself falls back to,
 * `https://atrium.agency`, does not resolve today — pointing monitors at it
 * would paint the dashboard red forever and teach everyone to ignore it.
 */
const PROD = (process.env.NEXT_PUBLIC_WEBSITE_URL ?? "").replace(/\/$/, "")

export const atriumWebsite: SystemDefinition = {
  id: "atrium-website",
  name: "Atrium website",
  category: "app",
  criticality: "critical",
  owner: "Atrium",
  workspace: "@atrium/website",
  summary: "The public marketing site: home, services, work, pricing, process, contact.",
  overview: `The front door. Next.js 16 on the App Router, built as a static site with a single
dynamic route (\`/contact\`). Everything a visitor sees is prerendered at build time, so an outage
here is almost always a deploy problem or a CDN problem, not a runtime one.

Case studies are data, not pages: \`lib/work.ts\` holds ten studies, and each one resolves its
media through an override chain. The site is designed to keep rendering when media is missing —
it degrades to placeholders rather than breaking the layout.`,
  sections: [
    {
      title: "How a case study finds its media",
      body: `Two asset paths exist, and the order matters:

1. \`lib/case-assets.overrides.ts\` — absolute URLs on \`cdn.atriumad.com\`. Hand-curated, wins when present.
2. \`lib/cloudinary-assets.generated.ts\` — generated by \`bun run sync:assets\` from the Cloudinary Admin API.

\`lib/work.ts:492\` picks the override first and falls back to the generated map. Four studies
(aahaa, chick-in-waffle, taco-naco, taha) have overrides and therefore survive a Cloudinary
outage; the other six do not.`,
    },
    {
      title: "Rendering and delivery",
      body: `\`next build\` emits 35 routes. \`/services/[slug]\` and \`/work/[slug]\` use
\`generateStaticParams\`, so adding a service or a case study to the data file is enough to create
its page — there is no route to write.

Images come from two remote hosts allowed in \`next.config.ts\`: the Cloudinary delivery domain and
\`cdn.atriumad.com\`. Anything else is blocked by \`next/image\` at request time.`,
    },
    {
      title: "Booking",
      body: `Cal.com is embedded lazily: \`CalEmbedProvider\` only injects the script when a
\`[data-cal-link]\` node exists on the page, so pages without a CTA pay nothing for it. The account
handles live in \`lib/cal.ts\` and \`lib/cta.ts\` — today those two disagree, which is tracked as a
known issue.`,
    },
  ],
  runbook: [
    {
      symptom: "Homepage returns a non-200",
      check: "Vercel deployment logs for the latest build; then the origin directly.",
      fix: "Roll back to the previous deployment in Vercel. The site is static, so a rollback is instant and safe.",
    },
    {
      symptom: "Pages load but case-study media is missing",
      check: "The Cloudinary monitor on this page. A 401 there explains every missing image at once.",
      fix: "Restore the Cloudinary account, or move the affected slugs into lib/case-assets.overrides.ts so they serve from the CDN.",
    },
    {
      symptom: "Sitemap or canonical URLs point at the wrong host",
      check: "NEXT_PUBLIC_SITE_URL in the deployment environment.",
      fix: "Set it explicitly; unset it falls back to https://atrium.agency silently.",
    },
  ],
  dependsOn: ["atrium-cdn", "cloudinary", "cal-com"],
  env: [
    {
      name: "NEXT_PUBLIC_SITE_URL",
      where: "apps/atrium.website/.env",
      purpose: "Canonical origin for metadata, sitemap and robots.",
      status: "missing",
      note: "Falls back to https://atrium.agency — a domain that does not resolve today (SERVFAIL). Every canonical URL, the sitemap and every OG tag are therefore pointing at nothing until this is set.",
    },
    {
      name: "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME",
      where: "apps/atrium.website/.env",
      purpose: "Cloud used to build every Cloudinary delivery URL.",
      status: "set",
    },
    {
      name: "CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET",
      where: "apps/atrium.website/.env",
      purpose: "Admin API auth for the asset sync script.",
      status: "script-only",
      note: "Only scripts/sync-cloudinary-assets.ts reads these. Absent from .env.example.",
    },
  ],
  entryPoints: [
    { label: "Case study data", path: "apps/atrium.website/lib/work.ts" },
    { label: "CDN asset overrides", path: "apps/atrium.website/lib/case-assets.overrides.ts" },
    { label: "Cloudinary URL builders", path: "apps/atrium.website/lib/cloudinary.ts" },
    { label: "Cal.com embed", path: "apps/atrium.website/components/ui/CalEmbedProvider.tsx" },
  ],
  links: PROD ? [{ label: "Production", href: PROD }] : [],
  monitors: PROD
    ? [
        {
          id: "website-home",
          label: "Homepage",
          meaning: "Nobody can reach the site at all.",
          url: PROD,
          expectStatus: [200],
          degradedAboveMs: 1500,
          timeoutMs: 10_000,
        },
        {
          id: "website-sitemap",
          label: "Sitemap",
          meaning: "Search engines lose the map of the site.",
          url: `${PROD}/sitemap.xml`,
          expectStatus: [200],
          expectBodyIncludes: "<urlset",
          degradedAboveMs: 2000,
        },
        {
          id: "website-work",
          label: "Work index",
          meaning: "The portfolio — the page sales actually sends people to — is down.",
          url: `${PROD}/work`,
          expectStatus: [200],
          degradedAboveMs: 2000,
        },
      ]
    : [
        {
          id: "website-home",
          label: "Homepage",
          meaning: "Nobody can reach the site at all.",
          url: "https://example.invalid",
          enabled: false,
          disabledReason:
            "Set NEXT_PUBLIC_WEBSITE_URL to the deployed site. atrium.agency does not resolve and atriumad.com currently serves the hosting default page, so there is no live site to watch yet.",
        },
      ],
  tags: ["next", "marketing", "static"],
}
